const bcrypt = require("bcryptjs");

const data = {
  users: [
    {
      name: "Mohit Tyagi",
      email: "mohit@gmail.com",
      password: bcrypt.hashSync("password", 8),
      isAdmin: true,
    },
    {
      name: "Raj Rishi",
      email: "raj@gmail.com",
      password: bcrypt.hashSync("password", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: "120",
      countInStock: 50,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Adidas Fit Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: "100",
      countInStock: 50,
      brand: "Adidas",
      rating: 4.7,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Woodland Safari Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: "200",
      countInStock: 50,
      brand: "Woodland",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      name: "Woodland Safari Cargo",
      category: "Trousers",
      image: "/images/p4.jpg",
      price: "500",
      countInStock: 50,
      brand: "Woodland",
      rating: 5,
      numReviews: 20,
      description: "high quality product",
    },
    {
      name: "Polo T Shirt",
      category: "T-Shirts",
      image: "/images/p5.jpg",
      price: "100",
      countInStock: 50,
      brand: "Polo",
      rating: 4.1,
      numReviews: 5,
      description: "high quality product",
    },
    {
      name: "Nike Jeans",
      category: "Trousers",
      image: "/images/p6.jpg",
      price: "200",
      countInStock: 0,
      brand: "Nike",
      rating: 4.2,
      numReviews: 18,
      description: "high quality product",
    },
  ],
};
module.exports = data;
